version: 0.2
phases:
  install:
    commands:
      - echo "No dependencies to install"
  build:
    commands:
      - mkdir -p build
      - cp index.html build/ # ビルドで index.html を生成
artifacts:
  files:
    - 'build/index.html' # アーティファクトとして保存するファイル
  base-directory: 'build' # ビルド後のベースディレクトリ



