version: 0.2
phases:
  install:
    commands:
      - echo "No dependencies to install"
  build:
    commands:
      - mkdir -p build
      - cp index.html build/
artifacts:
  files:
    - 'build/index.html'
  base-directory: 'build'

