version: 0.2
phases:
  install:
    commands:
      - echo "No dependencies to install"
  build:
    commands:
      - DEFAULT=`pwd`
      - mkdir -p build
      - cd build
      - cd $DEFAULT 
      - cp index.html build/
artifacts:
  files:
    - 'index.html'
  base-directory: 'build'
